on:
  push:
    branches:
      - master

name: Deploy master branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [us-west-1, us-west-2, us-east-1, us-east-2, ap-northeast-1, ap-northeast-2, ap-south-1, ap-southeast-1,
                 ap-southeast-2, ca-central-1, eu-central-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, eu-north-1]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: make chrome_aws_lambda.zip
        run: |
          git clone --depth=1 https://github.com/alixaxel/chrome-aws-lambda.git && \
          cd chrome-aws-lambda && \
          make chrome_aws_lambda.zip
      - name: publish
        run: |
          chmod +x publish.sh
          ./publish.sh
        env:
          TARGET_REGION: ${{ matrix.region }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}